### ISSUE TITLE
How to install in Fedora 24

### ISSUE THREAD

**Issue by timbo-lino** [jeromerobert/pdfshuffler#8]
Hi,

how can I install this on Fedora 24?

There is no package with the name python-cairo (only pycairo).

If i try it anyway i get this

```
KDEInit kann „pdfshuffler“ nicht starten:
Bibliothek „libkdeinit5_pdfshuffler“ lässt sich nicht öffnen.
Cannot load library libkdeinit5_pdfshuffler: (libkdeinit5_pdfshuffler: cannot open shared object file: No such file or directory)
```

**Comment by jeromerobert** [comment]
pycairo is the upstream name of the `python-cairo` Debian and Arch package, so it's a good candidate for the Fedora package name. Please just give it a try. If you can find the list of all Fedora needed packages I would gladly add it to the `README.md` file.

The error message puzzle me because:
* `libkdeinit5_pdfshuffler` does not exists in pdfshuffler and pdfshuffler as no relation with KDE.
* the message is in german, which I do not understand. Try to run `unset LANG` before running pdfshuffler.

**Comment by jeromerobert** [comment]
I close this bug because I've the feeling it won't get any update.
